import { redirect } from "next/navigation";

import { ClassForm } from "@/components/classes/class-form";
import { BookingActions, SessionBookingForm } from "@/components/classes/session-actions";
import { hasPermission, requireCurrentUser } from "@/lib/permissions/guards";
import { getClassFormOptions, listBookableMembers, listSchedule } from "@/server/services/classes";

function localDateTimeValue(value: Date): string { return value.toISOString().slice(0, 16); }
function dateTime(value: Date): string { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(value); }

export default async function ClassesPage() {
  const user = await requireCurrentUser();
  const canManage = hasPermission(user, "class.manage");
  const canBook = canManage || hasPermission(user, "class.book");
  if (!canManage && !canBook && !hasPermission(user, "class.read")) redirect("/dashboard");
  const [schedule, options, members] = await Promise.all([listSchedule(user), getClassFormOptions(user), listBookableMembers(user)]);
  return <div className="mx-auto max-w-6xl space-y-6"><section><p className="text-sm font-medium text-[var(--brand)]">Classes</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Class calendar & bookings</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">Upcoming sessions, capacity-safe bookings, deterministic waitlists, and attendance.</p></section>
    {canManage ? <section className="rounded-xl border bg-[var(--surface)] p-5"><h2 className="font-semibold">Create recurring class</h2><ClassForm branches={options.branches} startsAt={localDateTimeValue(new Date())} trainers={options.trainers} /></section> : null}
    <section className="space-y-4"><div><h2 className="font-semibold">Upcoming calendar</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">Sessions are listed chronologically in UTC.</p></div>{schedule.length === 0 ? <p className="rounded-xl border bg-[var(--surface)] p-8 text-center text-sm text-[var(--muted-foreground)]">No upcoming class sessions.</p> : schedule.map((session) => <article className="rounded-xl border bg-[var(--surface)] p-5" key={session.id}><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-lg font-semibold">{session.className}</h3><p className="mt-1 text-sm text-[var(--muted-foreground)]">{dateTime(session.startsAt)}–{new Intl.DateTimeFormat("en-GB", { timeStyle: "short", timeZone: "UTC" }).format(session.endsAt)} · {session.branchName}{session.room ? ` · ${session.room}` : ""}{session.trainerName ? ` · ${session.trainerName}` : ""}</p></div><span className="rounded-full bg-[var(--surface-muted)] px-3 py-1 text-xs font-semibold">{session.bookedCount}/{session.capacity} booked · {session.waitlistCount} waitlisted</span></div>{canBook && session.status === "SCHEDULED" && session.startsAt > new Date() ? <SessionBookingForm branchId={session.branchId} members={members} sessionId={session.id} /> : null}<div className="mt-4 grid gap-3 md:grid-cols-2"><section><h4 className="text-sm font-semibold">Roster</h4>{session.bookings.length === 0 ? <p className="mt-2 text-xs text-[var(--muted-foreground)]">No bookings yet.</p> : <ul className="mt-2 space-y-2">{session.bookings.map((booking) => <li className="rounded border p-2 text-sm" key={booking.id}><span className="font-medium">{booking.memberName}</span> <span className="text-xs text-[var(--muted-foreground)]">{booking.memberCode} · {booking.status}</span>{booking.status === "BOOKED" ? <BookingActions bookingId={booking.id} canManage={canManage} /> : null}</li>)}</ul>}</section><section><h4 className="text-sm font-semibold">Waitlist</h4>{session.waitlist.length === 0 ? <p className="mt-2 text-xs text-[var(--muted-foreground)]">No members waiting.</p> : <ol className="mt-2 space-y-2">{session.waitlist.map((entry) => <li className="rounded border p-2 text-sm" key={entry.id}>#{entry.position} <span className="font-medium">{entry.memberName}</span> <span className="text-xs text-[var(--muted-foreground)]">{entry.memberCode}</span></li>)}</ol>}</section></div></article>)}</section></div>;
}
